services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  aistor-server:
    image: quay.io/minio/aistor/minio:latest
    container_name: aistor-server
    command: minio server /mnt/data --license /minio.license
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${HOME}/minio/data:/mnt/data
      - ${HOME}/minio/minio.license:/minio.license
      - ${HOME}/minio/certs:/etc/minio/certs
    restart: unless-stopped